### ISSUE TITLE
Decide if want to generate SBML L3 V2 models, if yes, remove Fast attribute from Reaction

### ISSUE THREAD

**Issue by ayush9pandey** [WilliamIX/BioCRNPyler#2]
In Line 16, of `sbmlutil.py`, currently, SBML L3 V1 models are generated. If you decide to change it to L3, V2, then delete the line 145 (for setting `fast` attribute), as it is obsolete in the latest version.

**Comment by murrayrm** [comment]
Seems to me that `subsbml` should be able to input and output SBML using multiple versions, since that seems to be required for interfacing with current SBML tools.

For `BioCRNpyler`, I would say that it should be fine to pick any modern version of SBML and output in that format (L3 V1 seems like the easiest).
