### ISSUE TITLE
High Level Test Tube Interface

### ISSUE THREAD

**Issue by WilliamIX** [WilliamIX/BioCRNPyler#30]
- Single Mixture
- Add Components
- Constant Volume

**Comment by WilliamIX** [comment]
Can you make this a priority? It would be good to have it done so I can make example workbooks using this functionality. Thanks!

**Comment by ayush9pandey** [comment]
Yes, I hope to get this done within this week.

**Comment by ayush9pandey** [comment]
A first cut at this is available at my fork [here](https://github.com/ayush9pandey/BioCRNPyler/blob/master/examples/tutorial_gene_expression.py). 

I've added the new class and functions at appropriate places, some of which need to be implemented.

**Comment by WilliamIX** [comment]
Options for:
initial volume, initial concentration
final volume, final concentration

should be able to mix and match

**Comment by ayush9pandey** [comment]
Adding components
Volume options along with concentrations.
Having options for ConstitutivePromoter, RepressedPromoter etc.  (loading from a datasheet probably?)

**Comment by WilliamIX** [comment]
Yep, that sounds good! For repressed / activated promoters, look at my RegulatedPromoter class and regulated_promoter_activation_repression.py example.

I think that for the CRNlab interface, we can have a separate, internal config file which knows different promoter names, etc. and automatically creates the classes. We can add to this as we go.

**Comment by ayush9pandey** [comment]
1. Added option to create a mixture and optionally give extract and buffer names (to load parameters particularly for these extracts/buffers or to load extra parameters that are not loaded otherwise with the mixture that you are creating). 

2. Added option to add other components and load parameter dictionaries with them optionally.

3. Adding option for volumes along with concentrations. Now you can give volumes when adding a new mixture or a buffer, extract, dna etc. There are options to give final_conc with add_dna that decides the final value for its concentration. Instead, a user can give an initial_conc and a volume and let the software calculate the final concentration according to the total volume of the whole mixture.  
The final (updated) volume of the mixture is then set to the compartment volume in the SBML file. 

Creating a PR #38 with this basic version ready and working. In the near future, need to implement the file structure that would maintain the list of different promoters, etc. to make better UI. 

The latest tutorial file is availabe [here](https://github.com/ayush9pandey/BioCRNPyler/blob/master/examples/tutorial_CRNLab.py)

**Comment by WilliamIX** [comment]
PR worked with no problems. I'm looking through your example and your code and I have a couple of questions/comments:

- Unless I am mistaken, right now, the CRNLab class is a subclass of Mixture. This means that any particular functionality I put into a particular kind of Mixture, like BasicExtract or EnergyExtract or ExpressionExtract or TXTLExtract or whatever else we invent, won't be inherited by CRNLab. I think CRNlab, or whatever the "Tube" object is, should contain a single Mixture internally, not be a Mixture.
- In your example, it is very unclear how any kind of loading will work - what is your vision? Can you explain the parameter files you use in your examples? (I was thinking of fleshing that out so we could get a jupyter noteboook example file, but I think we're not quite there yet). 
-  When you add a component, just like adding DNA, you should be able to specify an initial concentration and volume or a final concentration, and it will set everything appropriately

**Comment by ayush9pandey** [comment]
1. The CRNLab object contains a single Mixture object internally. What's the source of this misunderstanding? Probably I need to fix how I have presented it. 

2. Right now, the parameters are loaded from csv files directly (user specifies the file name that has all the parameters and they get loaded) and I haven't yet looked into the new parameter loading methods you've added a few days ago, since most of the code in the PR was written before that. I will look into the new methods soon and think about if I want to stay with the current structure or what make changes 
to make.

**Comment by WilliamIX** [comment]
1. Look at the class definition: class CRNLab(Mixture): .... means Mixture is the superclass of the wrapper. Additionally, when you create a CRNLab (Which maybe we should still call a tube, but the wrapper being called CRNLab), it was unclear to me how you choose what kind of Mixture. I think I see that now in the examples you just posted. My hunch is you can just get rid of this inheritance and everything else will work (and my confusion was mostly due to the inheritance). I'd also advocate for being able to create a tube = Tube(extract = "blah", buffer = "blah"). Indeed, at some point we might also want Tube(cell_culture = "blah", media = "blah") - so just a big bunch of keywords to automatically populate the appropriate Models. I agree that we will probably have to get all these models sorted out via some kind of config file in the coming weeks.

2. My parameter system system is pretty well tested and documented. I suggest that we very simply just pass on the keywords parameter_file = [str file path], parameters = {parameter:val dictionary} as options whenever a tube is created/updated (in which case the parameter file/dict will be for the mixture) and whenever a component/dna assembly is added (in which case the parameter file/dict will be just for the component). I don't think I have a component.update_parameters or a Mixture.update_parameters function, but I will add them.

**Comment by ayush9pandey** [comment]
Ah, that CRNLab(Mixture) is something from earlier that I forgot to change. Thanks for pointing that out. 

You can do Tube(extract = "extract_file", buffer = "buffer_file") even now (and with some other arguments that are supported such as extract_volume, buffer_volume etc) and yeah it has a **kwargs to support other future developments.

**Comment by ayush9pandey** [comment]
> 
> 
> Options for:
> initial volume, initial concentration
> final volume, final concentration
> 
> should be able to mix and match
> 
> No Buffer - just different extracts. Some extracts will include energy as initial conditions.
> 
> A basic getting started workbook showing the easy to use functionality. This requires the high level wrappers (Tube-speak so to speak) to be written.

In the latest version of CRNLab (available on my fork of this repo), I have implemented these functions. Are there other things that we need for this class to be ready for the first "working" version of bioCRNpyler?

**Comment by zoltuz** [comment]
#51 added this feature.
